### ISSUE TITLE
Building process

### ISSUE THREAD

**Issue by ghost** [micfun123/unknownCoin#2]
Hey there! I would like to know how do you make this thing work, what version of Litecoin did you forked. I am willing to help if you could help me too. If it is possible, I would like to get in touch with you.

**Comment by micfun123** [comment]
I am using the Latest release 0.18.1 / 11 June 2020 of LiteCoin. you can get in touch with me though direct message on Twitter @michaelrbparker

**Comment by micfun123** [comment]
@Heaven-sFeel 

> Hey there! I would like to know how do you make this thing work, what version of Litecoin did you forked. I am willing to help if you could help me too. If it is possible, I would like to get in touch with you.

Edit I forked 0.8  git clone -b 0.8 https://github.com/litecoin-project/litecoin.git

**Comment by ghost** [comment]
I forked the same version and I'm struggling with the compilation process. I'm trying to make a windows executable.

**Comment by micfun123** [comment]
My Ubuntu build is playing up currently I am looking in to moving in to a newer version of litecoin

**Comment by Heaven-sFeel** [comment]
I followed u on Twitter, we can contribute to each other's project. But first we should discuss what we want to do.

**Comment by ghost** [comment]
I followed u on Twitter, we can contribute to each other's project. But first we should discuss what we want to do.

**Comment by micfun123** [comment]
Can this issue thread be closed?
